_crm/urls.py
from django.conf.urls.static import static
from django.conf import settings
from django.contrib import admin
from django.urls import path, include
from clients.views import LandingPageView
from django.contrib.auth.views import LoginView, LogoutView
from allauth.account.views import EmailView
from accounts.views import CustomPasswordChangeView, OrganizorEmailView
#from accounts.views import SignUpView

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', LandingPageView.as_view(), name='landing-page'),
    path('clients/', include('clients.urls', namespace='clients')),
    path('agents/', include('agents.urls', namespace='agents')),
    path('categories/', include('categories.urls', namespace='categories')),
    path('profile/', include('accounts.urls', namespace='profile')),
    path('accounts/password/change/', CustomPasswordChangeView.as_view(), name='change-password'),
    path('accounts/email/', OrganizorEmailView.as_view(), name='account_email'),
    path('accounts/', include('allauth.urls')),
    path('login/', LoginView.as_view(), name='login'),
    path('logout/', LogoutView.as_view(), name='logout'),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

agents/urls.py
from django.urls import path
from agents.views import AgentCreateView, AgentListView, AgentDetailView, AgentDeleteView, AgentUpdateView, AgentAssignView

app_name = 'agents'

urlpatterns = [
    path('', AgentListView.as_view(), name='agent-list'),
    path('add/', AgentCreateView.as_view(), name='agent-form'),
    path('<int:pk>/', AgentDetailView.as_view(), name='agent-detail'),
    path('<int:pk>/delete/', AgentDeleteView.as_view(), name='agent-delete'),
    path('<int:pk>/update/', AgentUpdateView.as_view(), name='agent-update'),
    path('<int:pk>/assign/', AgentAssignView.as_view(), name='agent-assign'),
]

agents/models.py
from django.db import models
from accounts.models import User, Organization
from django.db.models.signals import post_delete
from django.dispatch import receiver

# Create your models here.
class Agent(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    organization = models.ForeignKey(Organization, on_delete=models.CASCADE)

    def __str__(self):
        return self.user.username


# Signal to delete the associated User when an Agent is deleted
@receiver(post_delete, sender=Agent)
def delete_associated_user(sender, instance, **kwargs):
    if instance.user:
        instance.user.delete()

agents/forms.py
from django import forms
from accounts.models import User
from agents.models import Agent
from clients.models import Client
from django.core.exceptions import ValidationError

class AgentUpdateForm(forms.ModelForm):
    email = forms.EmailField()
    username = forms.CharField(max_length=15)
    first_name = forms.CharField(max_length=20, required=False)
    last_name = forms.CharField(max_length=20, required=False)

    class Meta:
        model = Agent
        exclude = ['user','organization']

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        if self.instance and self.instance.user:
            self.fields['email'].initial = self.instance.user.email
            self.fields['username'].initial = self.instance.user.username
            self.fields['first_name'].initial = self.instance.user.first_name
            self.fields['last_name'].initial = self.instance.user.last_name

    def clean_email(self):
        email = self.cleaned_data.get('email')
        if not email:
            raise ValidationError("Email is required.")

        # Check if the email is already in use by another user
        user_with_email = User.objects.filter(email=email).exclude(pk=self.instance.user.pk).first()
        if user_with_email:
            raise ValidationError("This email is already in use by another user.")

        return email

    def save(self, commit=True):
        agent = super().save(commit=False)
        if commit:
            agent.save()
            user = agent.user
            user.email = self.cleaned_data['email']
            user.username = self.cleaned_data['username']
            user.first_name = self.cleaned_data['first_name']
            user.last_name = self.cleaned_data['last_name']
            user.save()
        return agent


class AgentCreateForm(forms.ModelForm):
    class Meta:
        model = User
        fields =  [
            'email',
            'username',
            'first_name',
            'last_name',
        ]

class AgentAssignForm(forms.ModelForm):
    class Meta:
        model = Client
        fields = ['agent']

    agent = forms.ModelChoiceField(queryset=Agent.objects.none(), required=False)

    # To override the agent field so organizations only can assign their agents to a client
    def __init__(self, *args, **kwargs):
        request = kwargs.pop('request')
        organization = request.user.organization
        agents = Agent.objects.filter(organization=organization)
        super(AgentAssignForm, self).__init__(*args, **kwargs)
        self.fields['agent'].queryset = agents

agents/views.py
from random import randint
from django.shortcuts import reverse
from django.views.generic import CreateView, ListView, DetailView, DeleteView, UpdateView, FormView
from agents.forms import AgentUpdateForm, AgentAssignForm, AgentCreateForm
from agents.mixins import LoginAndOrganizorRequiredMixin
from agents.models import Agent
from django.core.mail import send_mail
from clients.models import Client

# Create your views here.

class AgentListView(LoginAndOrganizorRequiredMixin, ListView):
    template_name = 'agent/agent_list.html'

    # to show agents related only to the user
    def get_queryset(self):
        organization = self.request.user.organization
        return Agent.objects.filter(organization=organization)

class AgentCreateView(LoginAndOrganizorRequiredMixin, CreateView):
    form_class = AgentCreateForm
    template_name = 'agent/agent_form.html'

    def get_success_url(self):
#       return reverse('agents:agent-list')
        return reverse('agents:agent-detail', args=[self.object.pk])

    # when an agent is add by the organization, an agent user is automatically created
    def form_valid(self, form):
        user = form.save(commit=False)
        user.is_organizor = False
        user.is_agent = True

        # create a random password for the new agent
        user.set_password(f'{randint(0,1000000)}')
        user.save()

        Agent.objects.create(
            user=user,
            organization=self.request.user.organization
        )

        send_mail(
            subject='Email invitation',
            message=f'Please visit the website to confirm your account and set a new password' + '\n'                    
                    f'Username: {user.username}' + '\n' 
                    f'http://127.0.0.1:8000/accounts/password/reset/',
            from_email='thenamelessone@gmail.com',
            recipient_list=['kemo@gmail.com']
        )

        return super(AgentCreateView, self).form_valid(form)

class AgentDetailView(LoginAndOrganizorRequiredMixin, DetailView):
    template_name = 'agent/agent_detail.html'

    def get_queryset(self):
        organization = self.request.user.organization
        return Agent.objects.filter(organization=organization)

class AgentDeleteView(LoginAndOrganizorRequiredMixin, DeleteView):
    template_name = 'agent/agent_delete.html'

    def get_success_url(self):
        return reverse('agents:agent-list')

    def get_queryset(self):
        organization = self.request.user.organization
        return Agent.objects.filter(organization=organization)

class AgentUpdateView(LoginAndOrganizorRequiredMixin, UpdateView):
    form_class = AgentUpdateForm
    template_name = 'agent/agent_update.html'

    def get_success_url(self):
        return reverse('agents:agent-detail', args=[self.object.pk])

    def get_queryset(self):
        organization = self.request.user.organization
        return Agent.objects.filter(organization=organization)

class AgentAssignView(LoginAndOrganizorRequiredMixin, UpdateView):
    template_name = 'agent/agent_assign.html'
    form_class = AgentAssignForm
    queryset = Client.objects.all()

    # it helps to override the agent field in the AgentAssignForm
    def get_form_kwargs(self, **kwargs):
        kwargs = super(AgentAssignView, self).get_form_kwargs(**kwargs)
        kwargs.update({'request': self.request})
        return kwargs

    def get_queryset(self):
        user = self.request.user

        # organization only see their clients
        if user.is_organizor:
            queryset = Client.objects.filter(organization__user=user)

        # Agents only see their clients
        elif user.is_agent:
            queryset = Client.objects.filter(agent__user=user)

        return queryset

    def get_success_url(self):
        return reverse('clients:client-detail', args=[self.object.pk])

templates/agent/agent_assign.html
{% extends 'partials/base.html' %}
{% load tailwind_filters %}
    {% block content %}
<div class="max-w-sm mx-auto text-white">
    <br>
    <h2 class="sm:text-3xl text-2xl font-medium">Assign Agent</h2>
	<br>
    <form method="post" >
        {% csrf_token %}
        {{form|crispy}}
        <button type="submit" class="w-47.25 text-white bg-green-600 hover:bg-green-800 px-1 py-2 rounded-md">Submit
        </button>
            <a href="{{ view.get_success_url }}" class="btn btn-secondary">
        <button type="button" class="mt-2 w-47.5 text-white bg-blue-600 hover:bg-blue-800 px-1 py-2 rounded-md">Cancel
    </button>
            </a>
    </form>
</div>
    {% endblock %}

templates/agent/agent_delete.html
{% extends 'partials/base.html' %}
{% load tailwind_filters %}
    {% block content %}
<div class="max-w-sm mx-auto text-white">
    <br>
    <h2 class="sm:text-3xl text-2xl font-medium">Delete Agent</h2>
	<br>
        <br>
    <p class="sm:text-xl text-xl font-medium">Do you want to delete the agent?</p>
	<form method="post" >
        {% csrf_token %}
        {{form|crispy}}
        <button type="submit" class="w-47.25 text-white bg-green-600 hover:bg-green-800 px-1 py-2 rounded-md">Submit
        </button>
            <a href="{% url 'agents:agent-detail' agent.pk %}" class="btn btn-secondary">
        <button type="button" class="mt-2 w-47.5 text-white bg-blue-600 hover:bg-blue-800 px-1 py-2 rounded-md">Cancel
    </button>
            </a>
    </form>
</div>
    {% endblock %}

templates/agent/agent_detail.html
{% extends 'partials/base.html' %}
    {% block content %}

<section class=" mr-40 text-white  body-font">
  <div class=" container px-5 py-24 mx-auto">
    <div class="flex items-center lg:w-2/3 mx-auto  mb-10  sm:flex-row flex-col">
      <div class="sm:w-32 sm:h-32 h-20 w-20 sm:mr-10 inline-flex items-center justify-center rounded-full text-red-400 bg-gray-800 flex-shrink-0">
        <svg fill="none" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" class="sm:w-16 sm:h-16 w-10 h-10" viewBox="0 0 24 24">
          <path d="M22 12h-4l-3 9L9 3l-3 9H2"></path>
        </svg>
      </div>
      <div class="flex-grow sm:text-left text-center mt-6 sm:mt-0">
        <h2 class="text-white text-lg title-font font-medium mb-3" style="font-weight:bold">{{agent.user.first_name}} {{agent.user.last_name}}</h2>

                  <div class="flex border-t border-gray-800 py-2">
          <span class="text-black">Username</span>
          <span class="ml-auto text-white">{{agent.user.username}}</span>
        </div>

                  <div class="flex border-t border-gray-800 py-2">
          <span class="text-black">Email</span>
          <span class="ml-auto text-white">{{agent.user.email}}</span>
        </div>

                  <div class="flex border-t border-gray-800 py-2">
          <span class="text-black">First Name</span>
          <span class="ml-auto text-white">{{agent.user.first_name|title}}</span>
        </div>

                          <div class="flex border-t border-gray-800 py-2">
          <span class="text-black">Last Name</span>
          <span class="ml-auto text-white">{{agent.user.last_name|title}}</span>
        </div>

         <a href="{% url 'agents:agent-update' agent.pk %}"><button class="inline-flex mt-10 ml-auto text-white bg-yellow-600 border-0 py-2 px-12 focus:outline-none hover:bg-yellow-700 rounded">Update </button></a>
         <a href="{% url 'agents:agent-delete' agent.pk %}"><button class="inline-flex mt-10 ml-auto text-white bg-orange-600 border-0 py-2 px-12 focus:outline-none hover:bg-orange-800 rounded">Delete</button></a>
      </div>
    </div>
</section>
{% endblock %}

templates/agent/agent_form.html
{% extends 'partials/base.html' %}
{% load tailwind_filters %}
    {% block content %}
<div class="max-w-sm mx-auto text-white py-8">
    <h2 class="sm:text-3xl text-2xl font-medium">Add Agent</h2>
	<br>
	<form method="post">
        {% csrf_token %}
        {{form|crispy}}
        <button type="submit" class="w-47.25 text-white px-1 py-2 rounded-md bg-green-600 hover:bg-green-800">Submit
        </button>
        <a href="{% url 'agents:agent-list' %}">
        <button type="button" class="mt-2 w-47.5 text-white px-1 py-2 rounded-md bg-blue-600 hover:bg-blue-800">Cancel
    </button>
            </a>

    </form>
</div>
    {% endif %}
    {% endblock %}

templates/agent/agent_list.html
{% extends 'partials/base.html' %}
    {% block content %}

<section class="text-white body-font">
  <div class="container py-15 mx-auto"  >
    <div class="flex flex-col text-center w-full mb-20">
      <h1 class="sm:text-4xl text-2xl font-medium title-font text-white">Agents</h1>
    </div>

      {% if object_list|length == 0 %}
<div style="display: flex; flex-direction: column; align-items: center; justify-content: center; height: 100%;">
  <p style="font-size: 1.5rem; font-weight: bold; margin-bottom: 1rem;">You have not added any agents yet.</p>
  <a href="{% url 'agents:agent-form' %}">
    <button type="submit" style="width: 12rem; color: white; padding: 0.5rem 1rem; border-radius: 0.375rem; background-color: #16a34a; hover:bg-green-800;">Add Agent +</button>
  </a>
</div>
        {% else %}

    <div class="flex flex-wrap -m-7">
   {% for agent in object_list %}

      <div class="p-4 md:w-1/4" >
              <a href="{% url 'agents:agent-detail' agent.pk %}">
        <div class="flex rounded-lg h-full p-4 flex-col" style="background-color:#990000">
          <div class= "flex justify-center">
            <h2 class="text-white title-font font-medium" style="font-weight:bold">{{agent.user.username}}
            </h2>
          </div>
          <div class="flex-grow">
          </div>
        </div>
      </div>
            </a>

        {% endfor %}
      {% endif %}
    </div>
  </div>
</section>
{% endblock %}

templates/agent/agent_update.html
{% extends 'partials/base.html' %}
{% load tailwind_filters %}
    {% block content %}
<div class="max-w-sm mx-auto text-white py-8">
    <h2 class="sm:text-3xl text-2xl font-medium">Update Agent</h2>
	<br>
	<form method="post">
        {% csrf_token %}
        {{form|crispy}}
        <button type="submit" class="w-47.25 text-white px-1 py-2 rounded-md bg-green-600 hover:bg-green-800">Submit
        </button>
        <a href="{% url 'agents:agent-detail' agent.pk %}">
        <button type="button" class="mt-2 w-47.5 text-white px-1 py-2 rounded-md bg-blue-600 hover:bg-blue-800">Cancel
    </button>
            </a>
    </form>
</div>
    {% endblock %}