_crm/urls.py
from django.conf.urls.static import static
from django.conf import settings
from django.contrib import admin
from django.urls import path, include
from clients.views import LandingPageView
from django.contrib.auth.views import LoginView, LogoutView
from allauth.account.views import EmailView
from accounts.views import CustomPasswordChangeView, OrganizorEmailView
#from accounts.views import SignUpView

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', LandingPageView.as_view(), name='landing-page'),
    path('clients/', include('clients.urls', namespace='clients')),
    path('agents/', include('agents.urls', namespace='agents')),
    path('categories/', include('categories.urls', namespace='categories')),
    path('profile/', include('accounts.urls', namespace='profile')),
    path('accounts/password/change/', CustomPasswordChangeView.as_view(), name='change-password'),
    path('accounts/email/', OrganizorEmailView.as_view(), name='account_email'),
    path('accounts/', include('allauth.urls')),
    path('login/', LoginView.as_view(), name='login'),
    path('logout/', LogoutView.as_view(), name='logout'),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

agents/urls.py
from django.urls import path
from agents.views import AgentCreateView, AgentListView, AgentDetailView, AgentDeleteView, AgentUpdateView, AgentAssignView

app_name = 'agents'

urlpatterns = [
    path('', AgentListView.as_view(), name='agent-list'),
    path('add/', AgentCreateView.as_view(), name='agent-form'),
    path('<int:pk>/', AgentDetailView.as_view(), name='agent-detail'),
    path('<int:pk>/delete/', AgentDeleteView.as_view(), name='agent-delete'),
    path('<int:pk>/update/', AgentUpdateView.as_view(), name='agent-update'),
    path('<int:pk>/assign/', AgentAssignView.as_view(), name='agent-assign'),
]

categories/urls.py
from django.urls import path
from categories.views import CategoryListView, CategoryDetailView, ClientCategoryUpdateView, CategoryCreateView, CategoryUpdateView, CategoryDeleteView

app_name = 'categories'

urlpatterns = [
    path('', CategoryListView.as_view(), name='category-list'),
    path('create/', CategoryCreateView.as_view(), name='category-create'),
    path('<int:pk>/detail/', CategoryDetailView.as_view(), name='category-detail'),
    path('<int:pk>/delete/', CategoryDeleteView.as_view(), name='category-delete'),
    path('<int:pk>/update/', CategoryUpdateView.as_view(), name='category-update'),
    path('<int:pk>/client-update/', ClientCategoryUpdateView.as_view(), name='client-category-update'),
]

clients/urls.py
from django.urls import path
from clients.views import ClientListView, ClientDetailView, ClientCreateView, ClientUpdateView, ClientDeleteView

app_name = 'clients'

urlpatterns = [
    path('', ClientListView.as_view(), name='client-list'),
    path('<int:pk>/', ClientDetailView.as_view(), name='client-detail'),
    path('add/', ClientCreateView.as_view(), name='client-add'),
    path('<int:pk>/update/', ClientUpdateView.as_view(), name='client-update'),
    path('<int:pk>/delete/', ClientDeleteView.as_view(), name='client-delete'),

]

clients/models.py
from django.db import models
from django.core.validators import MinValueValidator, MaxValueValidator
from agents.models import Agent
from accounts.models import Organization
from categories.models import Category

# Create your models here.

class Client(models.Model): #this class stores the records of clients
    first_name = models.CharField(max_length=20)
    last_name = models.CharField(max_length=20)
    email = models.EmailField(blank=True, null=True)

    description = models.TextField(blank=True, null=True)
    age = models.IntegerField(validators=[MinValueValidator(18), MaxValueValidator(120)])
    phone_number = models.CharField(max_length=20)
    date_added = models.DateField(auto_now_add=True)
    sort_by_date = models.DateTimeField(auto_now_add=True)

    organization = models.ForeignKey(Organization, on_delete=models.CASCADE) # If an organization got deleted all clients under that organization will be deleted
    agent = models.ForeignKey(Agent, on_delete=models.SET_NULL, null=True, blank=True) # If an agent got deleted all clients under that agent will be set to null
    category = models.ForeignKey(Category, related_name='clients', on_delete=models.SET_NULL, null=True, blank=True) # If a category got deleted all clients under that category will be set to null

    def __str__(self):
        return f'{self.first_name} {self.last_name}'

clients/forms.py
from django import forms
from clients.models import Client
from agents.models import Agent

class ClientForm(forms.ModelForm):
    class Meta:
        model = Client
        exclude = ['organization']

    agent = forms.ModelChoiceField(queryset=Agent.objects.none())

    # To override the agent field so organizations only can assign their agents to a client
    def __init__(self, *args, **kwargs):
        request = kwargs.pop('request')
        organization = request.user.organization
        agents = Agent.objects.filter(organization=organization)
        super(ClientForm, self).__init__(*args, **kwargs)
        self.fields['agent'].required = False
        self.fields['agent'].queryset = agents

clients/views.py
from django.shortcuts import reverse
from clients.models import Client
from clients.forms import ClientForm
from django.views.generic import TemplateView, ListView, DetailView, DeleteView, CreateView, UpdateView
from django.contrib.auth.mixins import LoginRequiredMixin
from agents.mixins import LoginAndOrganizorRequiredMixin
# Create your views here.

class ClientDeleteView(LoginAndOrganizorRequiredMixin, DeleteView):
    template_name = 'client/client_delete.html'

    def get_success_url(self):
        return reverse('clients:client-list')

    def get_queryset(self):
        user = self.request.user

        # organizations only see their clients
        if user.is_organizor:
            queryset = Client.objects.filter(organization__user=user)

        return queryset

class ClientUpdateView(LoginAndOrganizorRequiredMixin, UpdateView):
    template_name = 'client/client_update.html'
    form_class = ClientForm
    queryset = Client.objects.all()

    # it helps to override the agent field in the AgentAssignForm
    def get_form_kwargs(self, **kwargs):
        kwargs = super(ClientUpdateView, self).get_form_kwargs(**kwargs)
        kwargs.update({'request': self.request})
        return kwargs

    def get_success_url(self):
        return reverse('clients:client-detail', args=[self.object.pk])

    def get_queryset(self):
        user = self.request.user

        # organizations only see their clients
        if user.is_organizor:
            queryset = Client.objects.filter(organization__user=user)

        return queryset

class ClientCreateView(LoginAndOrganizorRequiredMixin, CreateView):
    template_name = 'client/client_form.html'
    form_class = ClientForm

    # it helps to override the agent field in the AgentAssignForm
    def get_form_kwargs(self, **kwargs):
        kwargs = super(ClientCreateView, self).get_form_kwargs(**kwargs)
        kwargs.update({'request': self.request})
        return kwargs

    def get_success_url(self):
        return reverse('clients:client-list')

    def form_valid(self, form):
        # to set the client's organization as the user's organization by default
        form.instance.organization = self.request.user.organization
        return super(ClientCreateView, self).form_valid(form)

class ClientListView(LoginRequiredMixin, ListView):
    template_name = 'client/client_list.html'

    def get_queryset(self):
        user = self.request.user

        # Get the sort field and direction from the URL
        sort_field = self.request.GET.get('sort', 'sort_by_date')
        direction = self.request.GET.get('direction', 'asc')

        # Validate the sort field to prevent SQL injection
        valid_sort_fields = {'first_name', 'sort_by_date'}
        if sort_field not in valid_sort_fields:
            sort_field = 'first_name'

        # Add '-' prefix for descending order
        if direction == 'desc':
            sort_field = f'-{sort_field}'

        # Filter clients based on user role
        if user.is_organizor:
            queryset = Client.objects.filter(organization__user=user)
        elif user.is_agent:
            queryset = Client.objects.filter(agent__user=user)
        else:
            queryset = Client.objects.none()

        # Sort the queryset
        return queryset.order_by(sort_field)

    def get_context_data(self, **kwargs):
        # Add additional context data (sort_field and direction)
        context = super().get_context_data(**kwargs)
        context['sort_field'] = self.request.GET.get('sort', 'first_name')
        context['direction'] = self.request.GET.get('direction', 'asc')
        return context

class ClientDetailView(LoginRequiredMixin, DetailView):
    template_name = 'client/client_detail.html'

    def get_queryset(self):
        user = self.request.user

        # organizations only see their clients
        if user.is_organizor:
            queryset = Client.objects.filter(organization__user=user)

        # Agents only see their clients
        elif user.is_agent:
            queryset = Client.objects.filter(agent__user=user)

        return queryset

class LandingPageView(TemplateView):
    template_name = 'partials/landing_page.html'

templates/client/client_delete.html
{% extends 'partials/base.html' %}
{% load tailwind_filters %}
    {% block content %}
<title>Delete Client</title>
<div class="max-w-sm mx-auto text-white">
    <br>
    <h2 class="sm:text-3xl text-2xl font-medium">Delete Client</h2>
	<br>
        <br>
    <p class="sm:text-xl text-xl font-medium">Do you want to delete the Client?</p>
	<form method="post" >
        {% csrf_token %}
        {{form|crispy}}
        <button type="submit" class="w-47.25 text-white bg-green-600 hover:bg-green-800 px-1 py-2 rounded-md">Delete
        </button>
            <a href="{% url 'clients:client-detail' client.pk %}" class="btn btn-secondary">
        <button type="button" class="mt-2 w-47.5 text-white bg-blue-600 hover:bg-blue-800 px-1 py-2 rounded-md">Cancel
    </button>
            </a>
    </form>
</div>
    {% endblock %}

templates/client/client_detail.html
{% extends 'partials/base.html' %}
    {% block content %}

<title>{{client.first_name|title}} {{client.last_name|title}}</title>

<section class=" mr-40 text-white  body-font">
  <div class=" container px-5 py-24 mx-auto">
    <div class="flex items-center lg:w-2/3 mx-auto  mb-10  sm:flex-row flex-col">
      <div class="sm:w-32 sm:h-32 h-20 w-20 sm:mr-10 inline-flex items-center justify-center rounded-full text-red-400 bg-gray-800 flex-shrink-0">
        <svg fill="none" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" class="sm:w-16 sm:h-16 w-10 h-10" viewBox="0 0 24 24">
          <path d="M22 12h-4l-3 9L9 3l-3 9H2"></path>
        </svg>
      </div>
      <div class="flex-grow sm:text-left text-center mt-6 sm:mt-0">
        <h2 class="text-white text-lg title-font font-medium mb-3" style="font-weight:bold">{{client.first_name|title}} {{client.last_name|title}}</h2>

          <div class="flex border-t border-gray-800 py-2">
          <span class="text-black">Email</span>
          <span class="ml-auto text-white">{{client.email}}</span>
        </div>

                        <div class="flex border-t border-gray-800 py-2">
          <span class="text-black">Age</span>
          <span class="ml-auto text-white">{{client.age}}</span>
        </div>

                    <div class="flex border-t border-gray-800 py-2">
          <span class="text-black">Phone Number</span>
          <span class="ml-auto text-white">{{client.phone_number}}</span>
        </div>


                              <div class="flex border-t border-gray-800 py-2">
          <span class="text-black">Date Added</span>
          <span class="ml-auto text-white">{{client.date_added}}</span>
        </div>

                    <div class="flex border-t border-gray-800 py-2">
          <span class="text-black">Agent</span>
          <span class="ml-auto text-white">{{client.agent}}</span>
        </div>

                    <div class="flex border-t border-gray-800 py-2">
          <span class="text-black">Category</span>
          <span class="ml-auto text-white">{{client.category|title}}</span>
        </div>

        <div class="flex border-t border-gray-800 py-2">
          <span class="text-black">Description</span>
          <span class="ml-5 text-white" style="word-wrap: break-word; max-width: 500px;">{{client.description}}</span>
        </div>

        {% if user.is_organizor %}
          <a href="{% url 'clients:client-update' client.pk%}"> <button class="inline-flex mt-10 ml-auto text-white bg-yellow-600 border-0 py-2 px-7 focus:outline-none hover:bg-yellow-700 rounded">Update </button></a>
          <a href="{% url 'clients:client-delete' client.pk%}"> <button class="inline-flex mt-10 ml-auto text-white bg-orange-600 border-0 py-2 px-7.25 focus:outline-none hover:bg-orange-700 rounded">Delete</button></a>
          <a href="{% url 'agents:agent-assign' client.pk %}"> <button class="inline-flex mt-10 ml-auto text-white bg-purple-600 border-0 py-2 px-7 focus:outline-none hover:bg-purple-800 rounded">Assign Agent</button></a>
          <a href="{% url 'categories:client-category-update' client.pk %}"> <button class="inline-flex mt-10 ml-auto text-white bg-gray-600 border-0 py-2 px-7 focus:outline-none hover:bg-gray-700 rounded">Update Category</button></a>
        {% endif %}
      </div>

    </div>
</section>
{% endblock %}

templates/client/client_form.html
{% extends 'partials/base.html' %}
{% load tailwind_filters %}
    {% block content %}
<title>Add Client</title>
<div class="max-w-sm mx-auto text-white py-8">
    <h2 class="sm:text-3xl text-2xl font-medium">Add Client</h2>
	<br>
	<form method="post">
        {% csrf_token %}
        {{form|crispy}}
        <button type="submit" class="w-47.25 text-white px-1 py-2 rounded-md bg-green-600 hover:bg-green-800">Submit
        </button>
        <a href="{% url 'clients:client-list' %}">
        <button type="button" class="mt-2 w-47.5 text-white px-1 py-2 rounded-md bg-blue-600 hover:bg-blue-800">Cancel
    </button>
            </a>

    </form>
</div>
    {% endblock %}

templates/client/client_list.html
{% extends 'partials/base.html' %}
{% block content %}
<title>Clients</title>

<section class="text-gray-600 body-font">
  <div class="container px-5 py-17 mx-auto">
    <div class="flex flex-col text-center w-full mb-15">
      <h1 class="sm:text-4xl text-3xl font-medium title-font text-gray-100">Clients</h1>
    </div>
    <div class="lg:w-250 w-full mx-auto overflow-auto rounded-lg" style="background-color:#990000">
      <table class="table-auto w-full text-left whitespace-no-wrap">
        <thead>
          <tr>
            <!-- Name Column with Sorting -->
            <th class="bg-red-500 px-4 py-3 title-font tracking-wider font-medium text-black text-sm bg-gray-100 rounded-tl rounded-bl">
              <a href="?sort=first_name&direction={% if sort_field == 'first_name' and direction == 'asc' %}desc{% else %}asc{% endif %}" class="flex items-center">
                Name
                {% if sort_field == 'first_name' %}
                  {% if direction == 'asc' %}
                    <span class="ml-1">▲</span>
                  {% else %}
                    <span class="ml-1">▼</span>
                  {% endif %}
                {% endif %}
              </a>
            </th>

            <!-- Email Column -->
            <th class="bg-red-500 px-1 py-3 title-font tracking-wider font-medium text-black text-sm bg-gray-100">Email</th>

            <!-- Phone Number Column -->
            <th class="bg-red-500 py-3 title-font font-medium text-black text-sm bg-gray-100">Phone Number</th>

            <!-- Agent Column -->
            <th class="bg-red-500 px-4 py-3 title-font tracking-wider font-medium text-black text-sm bg-gray-100 pr-5">Agent</th>

            <!-- Category Column -->
            <th class="bg-red-500 px-14 py-3 title-font tracking-wider font-medium text-black text-sm bg-gray-100">Category</th>

            <!-- Sort By Date Column with Sorting -->
            <th class="bg-red-500 px-4 py-3 title-font tracking-wider font-medium text-black text-sm bg-gray-100">
              <a href="?sort=sort_by_date&direction={% if sort_field == 'sort_by_date' and direction == 'asc' %}desc{% else %}asc{% endif %}" class="flex items-center">
                Sort By Date
                {% if sort_field == 'sort_by_date' %}
                  {% if direction == 'asc' %}
                    <span class="ml-1">▲</span>
                  {% else %}
                    <span class="ml-1">▼</span>
                  {% endif %}
                {% endif %}
              </a>
            </th>

            <!-- Edit Column -->
            <th class="bg-red-500 w-10 title-font tracking-wider font-medium text-gray-900 text-sm bg-gray-100 rounded-tr rounded-br"></th>
          </tr>
        </thead>

        <tbody>
          {% if object_list|length == 0 %}
            <tr>
              <td colspan="7" class="px-4 py-3 text-center text-white">
      <p style="font-size: 1.5rem; font-weight: bold;">You have not added any clients yet.</p>
              <br>
                <a href="{% url 'clients:client-add' %}">
                <button type="submit" class="w-47.25 text-white px-1 py-2 rounded-md bg-green-600 hover:bg-green-800">Add Client +
        </button>
      </a>
              </td>
            </tr>
          {% else %}
            {% for client in object_list %}
              <tr>
                <td class="px-4 py-3 text-white text-sm capitalize">{{ client.first_name }} {{ client.last_name }}</td>
                <td class="px-1 py-3 text-white text-sm">{{ client.email }}</td>
                <td class="px- py-3 text-white text-sm">{{ client.phone_number }}</td>
                <td class="px-4 py-3 text-white text-sm">{{ client.agent }}</td>
                <td class="w-10 text-center text-white text-sm">{{ client.category|title }}</td>
                <td class="px-7 py-3 text-white text-sm">{{ client.sort_by_date|date:"Y-m-d" }}</td>  <!-- Updated field name -->
                <td class="text-green-400" style="padding-right: 20px;"><a href="{% url 'clients:client-detail' client.pk %}">View</a></td>
              </tr>
            {% endfor %}
          {% endif %}
        </tbody>
      </table>
    </div>
  </div>
</section>

{% endblock %}

templates/client/client_update.html
{% extends 'partials/base.html' %}
{% load tailwind_filters %}
    {% block content %}
<title>Update Client</title>
<div class="max-w-sm mx-auto text-white py-8">
    <h2 class="sm:text-3xl text-2xl font-medium">Update Client</h2>
	<br>
	<form method="post">
        {% csrf_token %}
        {{form|crispy}}
        <button type="submit" class="w-47.25 text-white px-1 py-2 rounded-md bg-green-600 hover:bg-green-800">Submit
        </button>
        <a href="{% url 'clients:client-detail' client.pk %}">
        <button type="button" class="mt-2 w-47.5 text-white px-1 py-2 rounded-md bg-blue-600 hover:bg-blue-800">Cancel
    </button>
            </a>
    </form>
</div>
    {% endblock %}